// <auto-generated />
using System;
using AidDashboard.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AidDashboard.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260630095933_AddServicesCatalog")]
    partial class AddServicesCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("AidDashboard.Domain.Accounts.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountManagerCrd")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AccountTypeRefId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApacSdm")
                        .HasColumnType("TEXT");

                    b.Property<string>("BuLeader")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("ClientHardware")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ConnectivityRefId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ContractEndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractSupervisor")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmeaLtsSdm")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmeaSdm")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmeaSm")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("FlagshipAccount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GlobalSdm")
                        .HasColumnType("TEXT");

                    b.Property<string>("GlobalSm")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HeadquarterCountryRefId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IndustryRefId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ItsmToolRefId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("LaunchDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ManagedByRefId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("NaLtsSdm")
                        .HasColumnType("TEXT");

                    b.Property<string>("NaSdm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long?>("NoOfUsersSupported")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProjectTrainingDurationDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegionalOwnership")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("SharingConstraints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupportChannels")
                        .HasColumnType("TEXT");

                    b.Property<string>("TelecomCountry")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TelecomRefId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransformationManager")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tsm")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("WorkFromHomeApproved")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("AidDashboard.Domain.Accounts.AccountCountry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountryRefId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NoOfLtsStaff")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("NoOfUsers")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "CountryRefId")
                        .IsUnique();

                    b.ToTable("AccountCountries");
                });

            modelBuilder.Entity("AidDashboard.Domain.Accounts.AccountMultiSelectValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Field")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReferenceItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Field", "ReferenceItemId")
                        .IsUnique();

                    b.ToTable("AccountMultiSelectValues");
                });

            modelBuilder.Entity("AidDashboard.Domain.Accounts.Automation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CostOfImplementationOneTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeliveredByRefId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("DeploymentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<double?>("EfficiencyImpactFtePerMonth")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RunningCostMonthly")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Automations");
                });

            modelBuilder.Entity("AidDashboard.Domain.Accounts.ContractualLanguageCell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageRefId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationRefId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "LocationRefId", "LanguageRefId")
                        .IsUnique();

                    b.ToTable("ContractualLanguageCells");
                });

            modelBuilder.Entity("AidDashboard.Domain.Accounts.CountryDeviceCell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountCountryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceRefId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AccountCountryId", "DeviceRefId")
                        .IsUnique();

                    b.ToTable("CountryDeviceCells");
                });

            modelBuilder.Entity("AidDashboard.Domain.Accounts.Opportunity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeliveredByRefId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EstimatedContractDurationMonths")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("EstimatedMonthlyValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OpportunityTypeRefId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RelatedServiceRefId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StatusRefId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Opportunities");
                });

            modelBuilder.Entity("AidDashboard.Domain.Accounts.SlaKpi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Bonus")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanBeReported")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FinancialPenalties")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Formula")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MeasurementTypeRefId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetPercent")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TypeRefId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("SlaKpis");
                });

            modelBuilder.Entity("AidDashboard.Domain.Accounts.StaffingCell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationRefId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModelType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleRefId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "ModelType", "LocationRefId", "RoleRefId")
                        .IsUnique();

                    b.ToTable("StaffingCells");
                });

            modelBuilder.Entity("AidDashboard.Domain.Accounts.SupportHour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Coverage")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromMondayFriday")
                        .HasColumnType("TEXT");

                    b.Property<int>("LanguageRefId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<bool>("OnCallInterpretDhs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Sophie")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToMondayFriday")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "LanguageRefId")
                        .IsUnique();

                    b.ToTable("SupportHours");
                });

            modelBuilder.Entity("AidDashboard.Domain.Common.ChangeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("ChangeLogs");
                });

            modelBuilder.Entity("AidDashboard.Domain.Identity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AidDashboard.Domain.Reference.ReferenceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.HasIndex("Type", "Name")
                        .IsUnique();

                    b.ToTable("ReferenceItems");
                });

            modelBuilder.Entity("AidDashboard.Domain.Services.AccountServiceEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ContractEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("ExistsInCompany")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("OpportunityToProvide")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProvidedByRefId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("ProvidedByStefaniniGroup")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServiceItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "ServiceItemId")
                        .IsUnique();

                    b.ToTable("AccountServiceEntries");
                });

            modelBuilder.Entity("AidDashboard.Domain.Services.ServiceCatalogItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("ServiceCatalogItems");
                });

            modelBuilder.Entity("AidDashboard.Domain.Accounts.AccountCountry", b =>
                {
                    b.HasOne("AidDashboard.Domain.Accounts.Account", null)
                        .WithMany("Countries")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AidDashboard.Domain.Accounts.AccountMultiSelectValue", b =>
                {
                    b.HasOne("AidDashboard.Domain.Accounts.Account", null)
                        .WithMany("MultiSelectValues")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AidDashboard.Domain.Accounts.Automation", b =>
                {
                    b.HasOne("AidDashboard.Domain.Accounts.Account", null)
                        .WithMany("Automations")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AidDashboard.Domain.Accounts.ContractualLanguageCell", b =>
                {
                    b.HasOne("AidDashboard.Domain.Accounts.Account", null)
                        .WithMany("ContractualLanguageCells")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AidDashboard.Domain.Accounts.CountryDeviceCell", b =>
                {
                    b.HasOne("AidDashboard.Domain.Accounts.AccountCountry", null)
                        .WithMany("DeviceCells")
                        .HasForeignKey("AccountCountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AidDashboard.Domain.Accounts.Opportunity", b =>
                {
                    b.HasOne("AidDashboard.Domain.Accounts.Account", null)
                        .WithMany("Opportunities")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AidDashboard.Domain.Accounts.SlaKpi", b =>
                {
                    b.HasOne("AidDashboard.Domain.Accounts.Account", null)
                        .WithMany("SlaKpis")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AidDashboard.Domain.Accounts.StaffingCell", b =>
                {
                    b.HasOne("AidDashboard.Domain.Accounts.Account", null)
                        .WithMany("StaffingCells")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AidDashboard.Domain.Accounts.SupportHour", b =>
                {
                    b.HasOne("AidDashboard.Domain.Accounts.Account", null)
                        .WithMany("SupportHours")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AidDashboard.Domain.Services.AccountServiceEntry", b =>
                {
                    b.HasOne("AidDashboard.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AidDashboard.Domain.Services.ServiceCatalogItem", b =>
                {
                    b.HasOne("AidDashboard.Domain.Services.ServiceCatalogItem", null)
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AidDashboard.Domain.Accounts.Account", b =>
                {
                    b.Navigation("Automations");

                    b.Navigation("ContractualLanguageCells");

                    b.Navigation("Countries");

                    b.Navigation("MultiSelectValues");

                    b.Navigation("Opportunities");

                    b.Navigation("SlaKpis");

                    b.Navigation("StaffingCells");

                    b.Navigation("SupportHours");
                });

            modelBuilder.Entity("AidDashboard.Domain.Accounts.AccountCountry", b =>
                {
                    b.Navigation("DeviceCells");
                });

            modelBuilder.Entity("AidDashboard.Domain.Services.ServiceCatalogItem", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
